# -*- coding: utf-8 -*-
"""trabajofinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uTI-6qWKn1QCXRXg8ytzwLeEb9zgY23d
"""

#Creacion de la clase Pelicula
class Pelicula:
  def __init__(self,titulo : str, año : int,genero : str,pelicula_vista : bool) -> None:
    self._titulo = titulo
    self._año = año
    self._genero = genero
    self._pelicula_vista = pelicula_vista

  # DEFINIR GETTERS:
  def get_titulo(self):
    return self._titulo

  def get_año(self):
    return self._año

  def get_genero(self):
    return self._genero

  def get_pelicula_vista(self):
    return "Vista" if self._pelicula_vista else "No vista"


  # DEFINIR SETTERS:
  def set_titulo(self,titulo : str):
    self._titulo = titulo

  def set_año(self,año : str):
    self._año = año

  def set_genero(self,genero : str):
    self._genero = genero

  def set_pelicula_vista(self,estado : str):
    self._pelicula_vista = True if estado.capitalize() == "Vista" else False






  # METODO STRING...
  def __str__(self) -> str:
      return f"""
          Titulo: {self.get_titulo()}
          Año: {self.get_año()}
          Genero: {self.get_genero()}
          Estado: {self.get_pelicula_vista()}
          """

#DEFINICION DE CLASE CATALOGO DE PELICULAS.

class Catalogo_Peliculas:
  def __init__(self) -> None:
    self.peliculas = []
    self.cargar_catalogo()





# METODO PARA CARGAR LA LISTA PELICULAS (SELF.PELICULAS)......

  def cargar_catalogo(self):
        self.peliculas = []
        try:
          with open("Peliculas.txt","r") as archivo:
            for linea in archivo:
              if linea != "":
                l = linea.strip().split(",")
                estado = l[3]
              if estado == "Vista":
                l[3] = True
              else:
                l[3] = False
              pelicula = Pelicula(l[0],l[1],l[2],l[3])
              self.peliculas.append(pelicula)
        except:
          print("Hubo un error al cargar las peliculas en el sistema",end="\n")



  #CARGAR UNA "NUEVA" PELICULA AL CATALOGO.
  def cargar_pelicula(self,pelicula : Pelicula):
    try:
    #VERIFICAR QUE NO EXISTA LA PELICULA PREVIAMENTE...
      pelicula_existe = self.consultar_pelicula(pelicula.get_titulo())
      if pelicula_existe != True:
        # if pelicula.pelicula_vista == True:
        #   estado = "Vista"
        # else:
        #   estado = "No vista"

          with open("Peliculas.txt","a") as archivo:
            archivo.write(f"\n{pelicula.get_titulo()},{pelicula.get_año()},{pelicula.get_genero()},{pelicula.get_pelicula_vista()}")
            print("La pelicula fue cargada correctamente")
      else:
        print("No se puede cargar dicha pelicula en el catalogo porque ya existe",end="\n")
    except:
      print("Hubo un error al añadir la pelicula... Intenta más tarde",end="\n")

#MOSTRAR LAS PELICULAS PERO ELIGIENDO ENTRE VISTAS Y NO VISTAS...
  def listar_peliculas(self,pelicula_vista : bool):
    try:
      self.cargar_catalogo()
      if len(self.peliculas) <= 0:
        print("No hay peliculas en el catalogo para mostrar",end="\n")
        return

      if pelicula_vista == True:
        for pelicula in self.peliculas:
          if pelicula.get_pelicula_vista() == "Vista":
            print(pelicula)
      else:
        for pelicula in self.peliculas:
          if pelicula.get_pelicula_vista() == "No vista":
            print(pelicula)
    except:
      print("Hubo un error al listar las peliculas...Intenta más tarde",end="\n")



#METODO QUE ME PERMITE SABER SI UN A PELICULA EXISTE...
  def consultar_pelicula(self,titulo : str):
    try:
      pelicula_encontrada = False
      while type(titulo) != str:
        print("Debes ingresar un titulo para poder realizar la busqueda...",end="\n")

      with open("Peliculas.txt","r") as archivo:
        for linea in archivo:
          if linea != "":
            if linea.capitalize() == titulo.capitalize():
              pelicula_encontrada = True
    except:
      print(f"Hubo un error, al buscar la pelicula '{titulo}'",end="\n")
      return pelicula_encontrada




#METODO QUE ME PERMITE OBTENER LA POSICION DE UNA DET. PELICULA EN LA LISTA
#DE PELICULAS...
  def obtener_posicion(self,pelicula_obtener : str):
    self.peliculas = []
    try:
      posicion = -1
      self.cargar_catalogo()
      for i,pelicula in enumerate(self.peliculas):
            if pelicula._titulo.lower() == pelicula_obtener.lower():
              return i
    except:

      return posicion


#CREACION DEL METODO ELIMINAR PELICULA
  def eliminar_pelicula(self,pelicula_eliminar : str):
    try:
      self.cargar_catalogo()
      posicion = self.obtener_posicion(pelicula_eliminar)
      if posicion >= 0:
        del self.peliculas[posicion]

        with open("Peliculas.txt","w") as archivo:
                i = 0
                for pelicula in self.peliculas:

                    if pelicula._pelicula_vista == True:
                      estado = "Vista"
                    else:
                      estado = "No vista"
                    if i == 0:
                      archivo.write(f"{pelicula.get_titulo()},{pelicula.get_año()},{pelicula.get_genero()},{estado}")
                      i = i + 1
                    else:
                      archivo.write(f"\n{pelicula.get_titulo()},{pelicula.get_año()},{pelicula.get_genero()},{estado}")

                print(f"La pelicula '{pelicula_eliminar}' fue eliminada con exito!",end="\n")
      else:
        print(f"No se encontro '{pelicula_eliminar}' y por ende no se pudo eliminar la pelicula del catalogo...",end="\n")
    except:
      print(f"Hubo un error al eliminar la pelicula '{pelicula_eliminar}'",end="\n")








#METODO PARA ENCONTRAR PELICULAS A PARTIR DE UNA PALABRA CLAVE PERTENECIENTE AL
# TITULO....


  def buscar_palabra_clave(self,palabra : str):
      peliculas_encontradas = []
      try:
        self.cargar_catalogo()

        for pelicula in self.peliculas:
          if palabra.lower() in pelicula._titulo.lower():
            peliculas_encontradas.append(pelicula)


        return peliculas_encontradas
      except:
        print("Hubo un error al buscar la/s pelicula/s en el catalogo",end="\n")

def mostrar_peliculas(catalogo : Catalogo_Peliculas):
  resp = 0
  while resp <= 0 or resp >3:
     resp = int(input("""
  1.Ver peliculas vistas

  2.Ver peliculas NO vistas

  3.Cancelar
  """))

  if resp == 1:
    catalogo.listar_peliculas(True)
  elif resp == 2:
    catalogo.listar_peliculas(False)
  else:
    return

def crear_pelicula() -> Pelicula:
    entrada_incorrecta = True


    while entrada_incorrecta:
      try:
        titulo_nuevo = input("Ingresa el titulo de la pelicula: ")


        año_pelicula = int(input("Ingresa el año de estreno de la pelicula: "))

        genero_pelicula = input("Ingresa el genero de la pelicula: ")
        estado = input("¿Usted ya vio la pelicula? si/no: ").lower()

        if estado == "si" or estado == "no":
          if estado == "si":
            estado = True
          else:
            estado = False
          pelicula_nueva = Pelicula(titulo_nuevo,año_pelicula,genero_pelicula,estado)
        else:
          raise Exception
      except:
        print("Hubo un error... Intenta de nuevo")
        entrada_incorrecta = True
      else:
        entrada_incorrecta = False

    print("Pelicula creada correctamente",end="\n")
    return pelicula_nueva

catalogo_upso = Catalogo_Peliculas()
salir = False
print("Bienvenido a tu catalogo de peliculas...")
print("¿Como puedo ayudarte?: ")
while salir != True:
  respuesta = input(
  """
      1.Listar peliculas

      2.Cargar nueva pelicula

      3.Buscar una pelicula

      4.Eliminar una pelicula

      5.Salir
  """)

  if respuesta == "1":
    mostrar_peliculas(catalogo_upso)


  elif respuesta == "2":
    nueva_pelicula = crear_pelicula()
    if isinstance(nueva_pelicula,Pelicula):
      catalogo_upso.cargar_pelicula(nueva_pelicula)
    else:
      print("Hubo un error al cargar la nueva pelicula al catalogo.")

  elif respuesta == "3":
    nombre_pelicula = input("Buscar pelicula: ")
    peliculas = catalogo_upso.buscar_palabra_clave(nombre_pelicula)
    for pelicula in peliculas:
      print(pelicula)
  elif respuesta == "4":
    nombre_pelicula = input("Ingresa el nombre de la pelicula a eliminar: ")
    catalogo_upso.eliminar_pelicula(nombre_pelicula)
  elif respuesta == "5":
    print("Gracias por usar el programa. Hasta luego!",end="\n")
    salir = True
  else:
    print("\nOpción incorrecta... Intenta de nuevo")